#include "arduino_secrets.h"

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/05b64ab0-d073-476d-b953-a730978e1da5 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing
c:\Users\alvarjl3\Documents\Repos\MRDL\0-datalogger-ecm\README.md
  float latitude;
  float longitude;
  float rpm;
  float velocity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <SoftwareSerial.h>
#include <TinyGPS++.h>
SoftwareSerial swSer(5, 4); 
SoftwareSerial gpsSerial(0, 2);
#define GPS_BAUD 9600
TinyGPSPlus gps;   
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  gpsSerial.begin(GPS_BAUD);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information youâll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void checkGPS()
{
  if (gps.charsProcessed() < 10)
  {
    Serial.println(F("No GPS detected: check wiring."));
  }
}

void loop() {
  ArduinoCloud.update();
  rpm = swSer.parseFloat();
  Serial.print("RPM es");
  Serial.println(rpm);
  unsigned long start = millis();

  while (millis() - start < 1000) {
    while (gpsSerial.available() > 0) {
      gps.encode(gpsSerial.read());
    }
    if (gps.location.isUpdated()) {
      Serial.print("LAT: ");
      Serial.println(gps.location.lat(), 6);
      latitude = gps.location.lat(), 6;
      Serial.print("LONG: "); 
      Serial.println(gps.location.lng(), 6);
      longitude = gps.location.lng(), 6;
      Serial.print("SPEED (km/h) = "); 
      Serial.println(gps.speed.kmph()); 
      velocity = gps.speed.kmph();
      Serial.println("");
    }
  }
  
 
  // Your code here 
  
  
}


/*
  Since Rpm is READ_WRITE variable, onRpmChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onRpmChange()  {
  // Add your code here to act upon Rpm change
}



